### PR TITLE
NT-update-tablespaces

### PR DESCRIPTION
**Pull request by bashtanov**
update this single file from upstream

### CODE REVIEW

**Comment by bashtanov** [comment]
https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/manifests/server/tablespace.pp

**Comment by bashtanov** [comment]
yes!

**Comment by chaicesan** [comment]
This just stops puppet from overwriting changes that you make manually?

**Comment by bashtanov** [comment]
> This just stops puppet from overwriting changes that you make manually?

No, it rather allows us to use `postgresql::server::tablespace` if the directory is created explicitly by puppet's `file` resource with non-700 permissions.

**Pull request merged**
